Script started on Fri Dec 13 04:49:05 2013
[?1034hbash-3.2$ g++ *.cpp -o run
bash-3.2$ ./run
Enter the name of the file you wish to import: 
gun+arrests.csv
The data in the sessionS12 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None

please entr the name of the judge:
please enter the status:
please enter the verdict:
a
a
a
After adding JudgeEaston to sessionF12, the data in the sessionS12 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None

After adding JudgeEaston to sessionF12, the data in the sessionF12 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None
judge info:         a        a        a

After adding JudgeCarter to sessionS13, the data in the sessionF12 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None
judge info:         a        a        a

After adding JudgeCarter to sessionS13, the data in the sessionS13 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None
judge info:         a        a        a
judge info:                            

please enter ID:
please enter name:
please enter age:
please enter dob:
please enter sex:
please enter race:
please enter bail:
please enter da:
please enter jail time:
please enter sentence:
please enter docket info:
1
a
1
a
a
a
a
a
a
a
please enter docket name:
please enter docket date:
please enter charge 1 y or n:
please enter charge 2 y or n:
please enter charge 3 y or n:
please enter charge 4 y or n:
a
a
a
a
a
a
After adding JohnDoe to sessionS13, the data in the sessionS12 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None

After adding JohnDoe to sessionS13, the data in the sessionF12 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None
judge info:         a        a        a

After adding JohnDoe to sessionS13, the data in the sessionS13 roster is: 
defendant info:     39255Alan Sones       63  3/22/44        M        B        YJosue Parlier        NHouse arrest
docket info:        Y        Y        Y        N83-AT-0112971-2010   1/8/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     81102Lesley Silvis       58  8/15/48        M        B        YMorgan Archambault        Y24-48 months
docket info:        Y        Y        Y        N83-AT-0120541-2010  1/13/10

judge info: Darnell PoissantHeld on all charges     Plea
defendant info:     35135Claude London       56   6/3/51        M        U        YLance Harsch        Y48-96 months
docket info:        Y        Y        Y        Y83-AT-0228521-2010  2/22/10

judge info: Alvin SchlicherHeld on some charges     Plea
defendant info:     33026Sidney Widener       53  4/15/54        M        B        YJamie Louder        Y11.5-23 months
docket info:        Y        Y        Y        N83-AT-0209341-2010  2/10/10

judge info: Michel ThodeHeld on some charges     Plea
defendant info:     35688Eliseo Mccomb       50   8/1/56        M        B        YFlorencio Phelan        N     None
docket info:        Y        Y        Y        N83-AT-0232631-2010   8/6/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     61874Ken Yancey       50  3/22/57        M        W        YPublic Def.        NProbation
docket info:        Y        Y        Y        Y83-AT-0236721-2010  2/28/10

judge info: Damon EhrlichHeld on some charges     Plea
defendant info:     37318Buddy Swinger       49   9/1/57        M        B        YJamey Mullenax        N     None
docket info:        Y        N        N        Y83-AT-0136531-2010  1/17/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     43189Ronny Scuderi       49  1/11/58        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0101401-2010  9/11/10

judge info: Jeffery SevilleCase withdrawn by DA     None
defendant info:     75758Andrew Hori       48  8/31/58        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0148191-2010  1/19/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     68834Sabina Schiller       46 10/10/59        F        B        YRamon Lorenz        N     None
docket info:        Y        Y        Y        Y83-AT-0210401-2010 11/16/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     77392Loren Rochell       47  4/26/60        M        B        YJosue Parlier        N     None
docket info:        Y        N        N        Y83-AT-0136521-2010  1/17/10

judge info: Jean ShahanHeld on all charges     None
defendant info:     45024Tory Berumen       46  5/23/61        M        B        YWeldon Urbano        N     None
docket info:        Y        N        N        Y83-AT-0203271-2010   2/2/10

judge info: Darnell PoissantHeld on some charges     None
defendant info:     80021Randy Pribble       45 12/26/61        M        B        YPublic Def.        N     None
docket info:        Y        N        Y        Y83-AT-0225291-2010  1/28/10

judge info: Michel ThodeHeld on some charges     None
defendant info:     31995Virgil Claggett       44  7/16/63        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-1237351-2008   1/1/08

judge info: Nicolas BalHeld on some charges     None
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0108321-2010   1/6/10

judge info: Julian ToberHeld on some charges     Plea
defendant info:     33504Glenn Clermont       43  3/26/64        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0409501-2010   1/2/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     55221Zack Folmar       36  8/21/70        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0133851-2010  1/22/10

judge info: Alexander PartinCase withdrawn by DA     None
defendant info:     79579Alan Herriman       34 11/13/72        M        B        YPublic Def.        NProbation
docket info:        N        Y        Y        Y83-AT-0114781-2010  1/10/10

judge info: Vicente FanelliHeld on all charges     Plea
defendant info:     41636Rex Enders       34  3/21/73        M        B        YJamey Mullenax        N     None
docket info:        Y        Y        Y        Y83-AT-0235761-2010   2/4/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0200821-2010   2/6/10

judge info: Ryan VerneHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200801-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     57932Tyron Bach       32 10/20/74        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0200811-2010   2/6/10

judge info: Alvin SchlicherHeld on some charges     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125821-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     45140Fredrick Franzoni       32   5/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0125831-2010  1/17/10

judge info: Vicente FanelliDischarged LOP     None
defendant info:     35157Shane Farago       32  7/26/75        M        W        YHorace Deshields        N     None
docket info:        Y        Y        Y        N83-AT-0527542-2008   1/5/08

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     30229Tyson Rieth       31   8/9/75        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0422372-2008  2/27/08

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        Y        Y        Y        Y83-AT-0150451-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     77755Andra Fishman       31  4/24/76        M        B        YMoshe Broyles        N     None
docket info:        N        Y        Y        Y83-AT-0150461-2010  1/31/10

judge info: Keven JanzenDischarged LOE     None
defendant info:     53635Rosario Calabro       30   7/3/77        M        B        NRoscoe Merz        Y     LIFE
docket info:        Y        Y        Y        Y83-AT-0119971-2010 11/30/10

judge info: Carl MikelsHeld on all charges  Verdict
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232241-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232251-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     70798Ashton Smullen       29  9/19/77        M        W        YAngelo Carrasco        N     None
docket info:        N        Y        Y        Y83-AT-0232261-2010  2/25/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     75076Bradley Langdon       29  12/6/77        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0103551-2010   1/3/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208661-2010  2/10/10

judge info: Vicente FanelliCase withdrawn by DA     None
defendant info:     24090Benjamin Bunnell       29 12/17/77        M        B        YPublic Def.        N     None
docket info:        Y        N        N        Y83-AT-0208651-2010  1/13/10

judge info: Vicente FanelliDischarged LOE     None
defendant info:     63020Rolf Pretty       29  6/29/78        M        B        YPublic Def.        Y6-23 months
docket info:        N        Y        Y        N83-AT-0202231-2010   2/7/10

judge info: Julian ToberHeld on all charges     Plea
defendant info:     29732Salvatore Tracy       28 11/23/78        M        B        YZackary Selvy        N     None
docket info:        Y        Y        Y        Y83-AT-0112641-2010   1/8/10

judge info: Julian ToberHeld on all charges     None
defendant info:     77702Matt Turmelle       28  12/3/78        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0729792-2007  2/27/07

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     30789Ross Hillin       27  9/20/79        M        B        YFredric Kaplan        N     None
docket info:        Y        Y        Y        N83-AT-0113641-2010   1/9/10

judge info: Jeffery SevilleHeld on all charges     None
defendant info:     28904Craig Donatelli       26  8/18/80        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0204891-2010   2/9/10

judge info: Darnell PoissantCase withdrawn by DA     None
defendant info:     72580Ciera Misiewicz       26  5/18/81        M        W        YPublic Def.        N     None
docket info:        N        Y        Y        N83-AT-0220911-2010  2/18/10

judge info: Julian ToberCase withdrawn by DA     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NMichael Rizer        N     None
docket info:        Y        Y        Y        Y83-AT-0106841-2010 12/29/10

judge info: Ezra BerggrenHeld on all charges     None
defendant info:     41224Kyong Comes       25  9/29/81        M        B        NPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0106851-2010 12/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     65410Brendan Rauscher       24   4/4/83        M        W        YMariano Lasch        N     None
docket info:        Y        Y        Y        Y83-AT-0129771-2010   1/8/10

judge info: Jean ShahanCase withdrawn by DA     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        Y11.5-23 months
docket info:        N        Y        Y        Y83-AT-0211321-2010  2/11/10

judge info: Jeffery SevilleHeld on some charges     Plea
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211311-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     44713Dione Motyka       22   2/8/85        M        B        YBart Getz        N     None
docket info:        N        Y        Y        Y83-AT-0211301-2010  2/11/10

judge info: Jeffery SevilleDischarged LOE     None
defendant info:     30303Lady Epping       22   3/4/85        F        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0206361-2010  1/27/10

judge info: Alvin SchlicherDischarged LOP     None
defendant info:     47654Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        Y        Y        Y        Y83-AT-0203811-2010   1/7/10

judge info: Vicente FanelliHeld on all charges     None
defendant info:     27567Ronny Grogg       21   9/2/85        M        B        YPublic Def.        N     None
docket info:        N        Y        Y        Y83-AT-0203821-2010   1/9/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156241-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156251-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156261-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     29834Denny Spies       21  7/25/86        M        B        YOrval Peoples        N     None
docket info:        N        Y        Y        Y83-AT-0156271-2010   2/3/10

judge info: Newton BlockerDischarged     None
defendant info:     49105Leandro Wilmeth       20 12/10/86        M        B        YSolomon Mendivil        N     None
docket info:        N        Y        Y        Y83-AT-0116581-2010 12/20/10

judge info: Alexander PartinDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118161-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     36115Everett Bono       20  3/17/87        M        B        YEfrain Kyles        N     None
docket info:        N        Y        Y        Y83-AT-0118151-2010  7/15/10

judge info: Lino WeatherholtzDischarged LOP     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114671-2010  9/29/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/28/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114681-2010 10/12/10

judge info: Isaiah LandeCase withdrawn by DA     None
defendant info:     27168Joshua Mahurin       19  9/29/87        M        B        YBart Getz        N     None
docket info:        Y        Y        Y        Y83-AT-0114691-2010 12/20/10

judge info: Isaiah LandeCase withdrawn by DA     None
judge info:         a        a        a
judge info:                            
defendant info:         1        a        1        a        a        a        a        a        a        a
docket info:        a        a        a        a        a        a


run(1399,0x7fff76fdb310) malloc: *** error for object 0x7fff5d0539d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
bash-3.2$ exit
exit

Script done on Fri Dec 13 04:49:40 2013
